---
# Certbot
certbot_virtualenv_package_name: python3-virtualenv

certbot_admin_email: usegalaxy.it@gmail.it
certbot_agree_tos: --agree-tos
certbot_auth_method: --standalone
certbot_auto_renew: true
certbot_auto_renew_user: root
certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_domains:
  - "{{ server_names }}"
certbot_install_method: virtualenv
certbot_environment: production # !!! CHECK -> change to production
certbot_post_renewal: |
  systemctl restart nginx || true
certbot_share_key_users:
  - nginx

certbot_well_known_root: /srv/nginx/_well-known_root
